restaurant/urls.py
from django.urls import path

from . import views

app_name = 'restaurant'
urlpatterns = [
    path('', views.GeneralView.as_view(), name='restaurant_general_view'),
    path('create/', views.RestaurantCreate.as_view(), name='restaurant_create'),
    path('menu/create/', views.RestaurantMenuCreate.as_view(), name='restaurant_menu_create'),
    path('<int:pk>/', views.RestaurantUpdate.as_view(), name='restaurant_update'),
]

seerene/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView, RedirectView

urlpatterns = [
    path('restaurant/', include('restaurant.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='restaurant/')),
]

restaurant/models.py
from enum import Enum

from django.db import models


class RestaurantMenuType(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Restaurant(models.Model):
    class CATEGORY(Enum):
        FASTFOOD = ('FASTFOOD', 'Focus is primarily on quick service')
        FAMILYSTYLE = ('FAMILYSTYLE', 'Food served on large platters for parties to share')
        FINDINING = ('FINDINING', 'Formal dress code and fine dining etiquette')
        CASUALDINING = ('CASUALDINING', 'Moderately-priced menus')
        CAFE = ('CAFE', 'Usually serve coffee, tea, pastries, and small items for breakfast and lunch')

        @classmethod
        def get_value(cls, member):
            return cls[member].value[0]

    menu = models.ForeignKey(RestaurantMenuType, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    category = models.CharField(
        max_length=150,
        choices=[x.value for x in CATEGORY],
        default=CATEGORY.get_value('FASTFOOD'),
    )
    price_range = models.CharField(max_length=25, blank=True)
    buffet = models.BooleanField(default=False)
    smoking_room = models.NullBooleanField(default=False)

    def __str__(self):
        return self.name

restaurant/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView
from .models import Restaurant, RestaurantMenuType


class GeneralView(generic.ListView):
    template_name = 'restaurant/restaurant_list.html'
    context_object_name = 'restaurant_list'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            restaurant_list = Restaurant.objects.filter(name__icontains=query)
        else:
            restaurant_list = Restaurant.objects.all()
        return restaurant_list


class RestaurantMenuCreate(LoginRequiredMixin, CreateView):
    model = RestaurantMenuType
    fields = '__all__'
    template_name = 'restaurant/restaurant_menu_form.html'
    success_url = '/restaurant/create/'


class RestaurantCreate(LoginRequiredMixin, CreateView):
    class Meta:
        model = RestaurantMenuType
        fields = '__all__'

    model = Restaurant
    fields = '__all__'
    success_url = '/restaurant/'


class RestaurantUpdate(LoginRequiredMixin, UpdateView):
    class Meta:
        model = RestaurantMenuType
        fields = '__all__'

    model = Restaurant
    fields = '__all__'
    template_name_suffix = '_update_form'
    success_url = '/restaurant/'

restaurant/templates/restaurant/restaurant_form.html
{% block content %}
    {% if user.is_authenticated %}
        Logged in as {{ user.username }}! <a href="{% url 'logout' %}">logout</a>
        <br>
        <form method="post">{% csrf_token %}
            <p><a href={% url 'restaurant:restaurant_menu_create' %}> Create Restaurant Menu if you want </a></p>
            {{ form.as_p }}
            <input type="submit" value="Save">
        </form>
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}">login</a>
    {% endif %}
{% endblock %}

restaurant/templates/restaurant/restaurant_list.html
<p><a href={% url 'restaurant:restaurant_create' %}>Create A Restaurant</a></p>
<form method='GET'>
    <input type='text' name='q' value='{{ request.GET.q }}'>
    <input class="button" type='submit' value="Search Restaurant">
</form>
{% if restaurant_list %}
    <ul>
        {% for restaurant in restaurant_list %}
            <a href={% url 'restaurant:restaurant_update' restaurant.id %}>
                <li>
                    {{ restaurant.name }}
                    <p>Category : {{ restaurant.category }}</p>
                    <p>Price range : {{ restaurant.price_range }}</p>
                </li>
            </a>
        {% endfor %}
    </ul>
{% else %}
    <p>There is no restaurant!</p>
{% endif %}

restaurant/templates/restaurant/restaurant_menu_form.html
{% block content %}
    {% if user.is_authenticated %}
        Logged in as {{ user.username }}! <a href="{% url 'logout' %}">logout</a>
        <br>
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save">
        </form>
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}">login</a>
    {% endif %}
{% endblock %}

restaurant/templates/restaurant/restaurant_update_form.html
{% block content %}
    {% if user.is_authenticated %}
        Logged in as {{ user.username }}! <a href="{% url 'logout' %}">logout</a>
        <br>
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}">login</a>
    {% endif %}
{% endblock %}